# **Titanic Crisis Analysis — TCA**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [22]:
df["Age"].describe()

count    891.000000
mean      29.135993
std       13.495864
min        0.420000
25%       21.000000
50%       26.000000
75%       36.750000
max       80.000000
Name: Age, dtype: float64

In [ ]:
df['Title'] = df['Name'].str.extract(r', (\w+)\.', expand=False)

df['Age'] = df.groupby(['Sex', 'Pclass', 'Title']) ['Age'].transform(
    lambda x: x.fillna(x.median())
)

df['Age'] = df['Age'].fillna(df['Age'].median())

In [6]:
df["FamSize"] = df["SibSp"] + df["Parch"] + 1
df["FamSize"]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,FamSize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,18.0,1,2,W./C. 6607,23.4500,NaN,S,Miss,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,1

In [7]:
df = df.drop(columns=["SibSp", "Parch"])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,Title,FamSize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,Mr,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,Mrs,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,Miss,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,Mrs,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,Rev,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,Miss,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,18.0,W./C. 6607,23.4500,NaN,S,Miss,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,Mr,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,Mr,1

In [8]:
col = df.pop("FamSize")
df.insert(6,"FamSize",col)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,FamSize,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,2,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,2,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,1,STON/O2. 3101282,7.9250,NaN,S,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,2,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,1,373450,8.0500,NaN,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,1,211536,13.0000,NaN,S,Rev
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,1,112053,30.0000,B42,S,Miss
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,18.0,4,W./C. 6607,23.4500,NaN,S,Miss
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,1,111369,30.0000,C148,C,Mr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,1,370376,7.7500,NaN,Q,Mr

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
FamSize          0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Title            1
dtype: int64

In [11]:
df.shape

(891, 12)

# Cabin Deck Feature

In [15]:
df['Cabin'] = df['Cabin'].fillna('U')

df['CabinDeck'] = df['Cabin'].str[0]

df = df.drop(columns=['Cabin'])

# Log(1 + Fare): to make fare skewness more normalized

In [17]:
df['FareLog'] = np.log1p(df['Fare'])

df = df.drop(columns=['Fare'])

# Gender & Survival Rates

In [23]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [24]:
df["Sex"][(df["Survived"] == 1) & (df["Sex"] == "male")].count()

np.int64(109)

## ~18.9% Survival rate in TCA

In [25]:
df["Sex"][(df["Survived"] == 1) & (df["Sex"] == "female")].count()

np.int64(233)

## ~74.2% Survival rate in TCA

In [26]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

# Age & Survival Rates

In [27]:
((df["Age"] > 0) & (df["Age"] < 12)).sum()

np.int64(72)

In [28]:
df["Survived"][(df["Age"] > 0) & (df["Age"] < 12)].sum()

np.int64(41)

In [29]:
((df["Age"] > 13) & (df["Age"] < 20)).sum()

np.int64(126)

In [30]:
df["Survived"][(df["Age"] > 13) & (df["Age"] < 20)].sum()

np.int64(56)

In [31]:
((df["Age"] > 21) & (df["Age"] < 40)).sum()

np.int64(458)

In [32]:
df["Survived"][(df["Age"] > 21) & (df["Age"] < 40)].sum()

np.int64(160)

In [33]:
((df["Age"] > 41) & (df["Age"] < 90)).sum()

np.int64(151)

In [34]:
df["Survived"][(df["Age"] > 41) & (df["Age"] < 90)].sum()

np.int64(61)

In [35]:
df.groupby("Embarked")["Survived"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [36]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [37]:
df.groupby(["Embarked", "Pclass"]).size()

Embarked  Pclass
C         1          85
          2          17
          3          66
Q         1           2
          2           3
          3          72
S         1         127
          2         164
          3         353
dtype: int64

# Passenger Class & Survival

In [38]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

# Name Extraction

In [42]:
df['Title'] = df['Title'].replace({
    'Mlle': 'Miss',
    'Ms': 'Miss',
    'Mme': 'Mrs'
})

df['Title'] = df['Title'].replace([
    'Lady', 'Countess', 'Capt', 'Col', 'Don',
    'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer',
    'Dona'
], 'Rare')

In [43]:
result = df.groupby(["Title", "Age"])["Survived"].mean()

print(result.to_string())

Title   Age
Master  0.42     1.000000
        0.67     1.000000
        0.83     1.000000
        0.92     1.000000
        1.00     0.600000
        2.00     0.250000
        3.00     1.000000
        4.00     0.444444
        6.00     1.000000
        7.00     0.000000
        8.00     0.500000
        9.00     0.500000
        10.00    0.000000
        11.00    0.500000
        12.00    1.000000
Miss    0.75     1.000000
        1.00     1.000000
        2.00     0.333333
        3.00     0.500000
        4.00     1.000000
        5.00     1.000000
        6.00     0.500000
        7.00     1.000000
        8.00     0.500000
        9.00     0.000000
        10.00    0.000000
        11.00    0.000000
        13.00    1.000000
        14.00    0.666667
        14.50    0.000000
        15.00    1.000000
        16.00    0.833333
        17.00    0.750000
        18.00    0.581395
        19.00    1.000000
        20.00    0.000000
        21.00    0.571429
        22.00    0.777778
        23.00    0.750000
        24.00    0.800000
        25.00    0.333333
        26.00    1.000000
        27.00    1.000000
        28.00    0.666667
        29.00    1.000000
        30.00    0.900000
        30.50    0.000000
        31.00    0.666667
        32.00    1.000000
        32.50    1.000000
        33.00    1.000000
        34.00    1.000000
        35.00    1.000000
        36.00    1.000000
        37.00    0.000000
        38.00    0.666667
        39.00    1.000000
        40.00    1.000000
        41.00    1.000000
        42.00    1.000000
        45.00    0.000000
        50.00    0.666667
        54.00    1.000000
        58.00    1.000000
        63.00    1.000000
Mr      11.00    0.000000
        14.00    0.000000
        15.00    0.000000
        16.00    0.090909
        17.00    0.142857
        18.00    0.076923
        19.00    0.111111
        20.00    0.230769
        20.50    0.000000
        21.00    0.058824
        22.00    0.066667
        23.00    0.111111
        23.50    0.000000
        24.00    0.071429
        24.50    0.000000
        25.00    0.222222
        26.00    0.097087
        27.00    0.545455
        28.00    0.117647
        28.50    0.000000
        29.00    0.230769
        30.00    0.071429
        30.50    0.000000
        31.00    0.263158
        32.00    0.428571
        32.50    0.000000
        33.00    0.000000
        34.00    0.181818
        34.50    0.000000
        35.00    0.300000
        36.00    0.266667
        36.50    0.000000
        37.00    0.200000
        38.00    0.200000
        39.00    0.125000
        40.00    0.230769
        40.50    0.000000
        41.00    0.000000
        42.00    0.333333
        43.00    0.000000
        44.00    0.200000
        45.00    0.400000
        45.50    0.000000
        46.00    0.000000
        47.00    0.000000
        48.00    0.600000
        49.00    0.333333
        50.00    0.000000
        51.00    0.200000
        52.00    0.000000
        54.00    0.000000
        55.00    0.000000
        55.50    0.000000
        56.00    0.000000
        58.00    0.000000
        59.00    0.000000
        60.00    0.500000
        61.00    0.000000
        62.00    0.333333
        64.00    0.000000
        65.00    0.000000
        66.00    0.000000
        70.00    0.000000
        70.50    0.000000
        71.00    0.000000
        74.00    0.000000
        80.00    1.000000
Mrs     14.00    1.000000
        15.00    1.000000
        17.00    1.000000
        18.00    0.666667
        19.00    1.000000
        22.00    1.000000
        23.00    1.000000
        24.00    1.000000
        25.00    0.500000
        26.00    0.000000
        27.00    0.666667
        28.00    0.750000
        29.00    0.666667
        30.00    0.500000
        31.00    0.692308
        32.00    0.500000
        33.00    1.000000
        34.00    1.000000
        35.00    1.000000
        36.00    1.000000
        38.00    1.000000
        39.00    0.600000
        40.00    0.750000
        41.00    0.333333
        41.50    1.000000
        42.00    1.000000
        43.00    0.500000
        44.00    0.666667
        45.00    0.600000
        47.00    0.500000
        48.00    0.666667
        49.00    1.000000
        50.00    1.000000
        51.00    1.000000
        52.00    1.000000
        53.00    1.000000
        54.00    1.000000
        55.00    1.000000
        56.00    1.000000
        57.00    0.000000
        58.00    1.000000
        60.00    1.000000
        62.00    1.000000
        63.00    1.000000
Rare    23.00    0.000000
        27.00    0.000000
        28.00    0.000000
        32.00    1.000000
        38.00    0.000000
        40.00    0.000000
        42.00    0.000000
        44.00    0.000000
        45.00    0.000000
        48.00    1.000000
        49.00    1.000000
        50.00    1.000000
        51.00    0.000000
        52.00    1.000000
        54.00    0.000000
        56.00    1.000000
        57.00    0.000000
        60.00    0.000000
        70.00    0.000000

In [65]:
result = df.groupby(["Title", "Age"])["Survived"].mean()

print(result.to_string())

Title     Age
Capt      70     0.000000
Col       56     1.000000
          60     0.000000
Don       40     0.000000
Dr        23     0.000000
          32     1.000000
          40     0.000000
          44     0.000000
          49     1.000000
          50     1.000000
          54     0.000000
Jonkheer  38     0.000000
Major     45     0.000000
          52     1.000000
Master    0      1.000000
          1      0.777778
          2      0.250000
          3      1.000000
          4      0.400000
          6      1.000000
          7      0.000000
          8      0.500000
          9      0.500000
          10     0.000000
          11     0.500000
          12     1.000000
          25     0.500000
Miss      1      1.000000
          2      0.333333
          3      0.500000
          4      1.000000
          5      1.000000
          6      0.500000
          7      1.000000
          8      0.500000
          9      0.000000
          10     0.000000
          11     0.000000
          13     1.000000
          14     0.500000
          15     1.000000
          16     0.833333
          17     0.750000
          18     0.600000
          19     1.000000
          20     0.000000
          21     0.571429
          22     0.619048
          23     0.750000
          24     0.750000
          25     0.333333
          26     1.000000
          27     1.000000
          28     0.800000
          29     1.000000
          30     0.800000
          31     0.666667
          32     1.000000
          33     1.000000
          34     1.000000
          35     1.000000
          36     1.000000
          37     0.000000
          38     0.666667
          39     1.000000
          40     1.000000
          41     1.000000
          42     1.000000
          45     0.000000
          50     0.666667
          54     1.000000
          58     1.000000
          63     1.000000
Mr        11     0.000000
          14     0.000000
          15     0.000000
          16     0.090909
          17     0.142857
          18     0.076923
          19     0.111111
          20     0.214286
          21     0.058824
          22     0.066667
          23     0.111111
          24     0.062500
          25     0.101852
          26     0.230769
          27     0.545455
          28     0.105263
          29     0.230769
          30     0.125000
          31     0.300000
          32     0.400000
          33     0.000000
          34     0.166667
          35     0.300000
          36     0.250000
          37     0.200000
          38     0.200000
          39     0.125000
          40     0.214286
          41     0.000000
          42     0.333333
          43     0.000000
          44     0.200000
          45     0.400000
          46     0.000000
          47     0.000000
          48     0.600000
          49     0.333333
          50     0.000000
          51     0.200000
          52     0.000000
          54     0.000000
          55     0.000000
          56     0.000000
          58     0.000000
          59     0.000000
          60     0.500000
          61     0.000000
          62     0.333333
          64     0.000000
          65     0.000000
          66     0.000000
          70     0.000000
          71     0.000000
          74     0.000000
          80     1.000000
Mrs       14     1.000000
          15     1.000000
          17     1.000000
          18     0.666667
          19     1.000000
          22     0.750000
          23     1.000000
          24     1.000000
          25     0.500000
          26     0.000000
          27     0.666667
          28     0.750000
          29     0.666667
          30     0.500000
          31     0.750000
          32     0.500000
          33     1.000000
          34     1.000000
          35     1.000000
          36     1.000000
          38     1.000000
          39     0.600000
          40     0.750000
          41     0.333333
          42     1.000000
          43     0.500000
          44     0.666667
          45     0.600000
          47     0.500000
          48     0.666667
          49     1.000000
          50     1.000000
          51     1.000000
          52     1.000000
          53     1.000000
          54     1.000000
          55     1.000000
          56     1.000000
          57     0.000000
          58     1.000000
          60     1.000000
          62     1.000000
          63     1.000000
Rev       27     0.000000
          28     0.000000
          42     0.000000
          51     0.000000
          54     0.000000
          57     0.000000
Royalty   48     1.000000
Sir       49     1.000000

In [44]:
df.groupby("Title")["Survived"].value_counts()

Title   Survived
Master  1            23
        0            17
Miss    1           130
        0            55
Mr      0           436
        1            81
Mrs     1           100
        0            26
Rare    0            15
        1             7
Name: count, dtype: int64